version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: trip-planner-mysql
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
